name: Build, Test & Deploy
on:
  push:
    branches: main
    paths-ignore:
      - '/.gitignore'
      - '/readme.md'
      - '/.tests'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: windows-2019
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: pre-build
        shell: pwsh
        run: |
          Install-Module -Name Pester -MaximumVersion 4.10.1 -Verbose -Scope CurrentUser -SkipPublisherCheck -Force
          Install-Module PSScriptAnalyzer -Scope CurrentUser -SkipPublisherCheck -ErrorAction SilentlyContinue -Force
          Install-Module 7zip4PowerShell -Scope CurrentUser -SkipPublisherCheck -ErrorAction SIlentlyContinue -Force

      - name: build
        shell: pwsh
        run: |
          ./build.ps1

      - name: code quality test
        shell: pwsh
        run: |
          ./tests/codecheck.ps1
          
      - name: test module
        id: test_module
        uses: zyborg/pester-tests-report@v1
        with:
          include_paths: .tests
          exclude_tags: skip_ci
          report_name: module_tests
          report_title: My Module Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: dump test results
        shell: pwsh
        run: |
          Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
          Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
          Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'
          
      
